const testimonialData = [
  {
    id: "mara",
    name: "Mara Lin",
    role: "Sunday regular",
    text: "The sesame crunch is perfect. I think about this bagel on weekdays.",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=85",
    desktopPosition: "lg:left-[7%] lg:top-[15%]",
    mobilePosition: "left-[7%] top-[13%]",
    rotation: -5,
    entry: 0.06,
    sparkle: true,
  },
  {
    id: "noah",
    name: "Noah Reyes",
    role: "Neighborhood local",
    text: "A little messy, wildly delicious. Exactly how breakfast should be.",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=85",
    desktopPosition: "lg:right-[8%] lg:top-[13%]",
    mobilePosition: "right-[7%] top-[27%]",
    rotation: 4,
    entry: 0.22,
    sparkle: false,
  },
  {
    id: "ida",
    name: "Ida Park",
    role: "Coffee person",
    text: "I came for the coffee. Then the cinnamon raisin bagel changed the plan.",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=160&q=85",
    desktopPosition: "lg:left-[14%] lg:bottom-[13%]",
    mobilePosition: "left-[6%] top-[43%]",
    rotation: 3,
    entry: 0.39,
    sparkle: true,
  },
  {
    id: "alex",
    name: "Alex Morgan",
    role: "Office favorite",
    text: "We ordered one box for the team. That was a very optimistic mistake.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=160&q=85",
    desktopPosition: "lg:right-[15%] lg:bottom-[20%]",
    mobilePosition: "right-[6%] top-[59%]",
    rotation: -4,
    entry: 0.56,
    sparkle: false,
  },
  
];

export default testimonialData;
